# Generated by Django 4.0.2 on 2022-03-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='image',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, height_field=True, max_length=255, null=True, upload_to='perfil/', verbose_name='Imagen de perfil', width_field=True),
        ),
    ]
